__title__ = "konovels"
__description__ = "Make a readable online novels for Kindle or Duokan etc. "
__url__ = "https://github.com/TRSWNCA/konovels"
__version__ = "0.0.1"
__author__ = "TRSWNCA"
__author_email__ = "alex_passenger@outlook.com"
__license__ = "MIT License"
